name: galt
description: "Gestione aziendale logistica e trasporti"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.16.6
  font_awesome_flutter: ^9.2.0
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.15
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^5.0.0
  flutter_secure_storage: ^8.1.0
  image_picker: ^0.8.4+3
  firebase_storage: ^11.7.7
  url_launcher: ^6.0.13
  fluttertoast: ^8.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/three-trucks-grassy-sphere.jpg"  # Assicurati che il file sia un PNG e non abbia trasparenze indesiderate

flutter:
  uses-material-design: true
  assets:
    - assets/images/three-trucks-grassy-sphere.jpg  # Usa l'estensione .png per l'immagine
    - assets/images/default_profile.jpg  # Assicurati che il file default_profile.jpg sia presente
