// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB995fLi1synr_vmgRxKAd-2qWyUeKbMW4',
    appId: '1:445998895525:web:320aec1c6bdd9d824cd84c',
    messagingSenderId: '445998895525',
    projectId: 'galt-53dca',
    authDomain: 'galt-53dca.firebaseapp.com',
    storageBucket: 'galt-53dca.appspot.com',
    measurementId: 'G-YG63FX3RQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkG7vbIWH42VSgsRVR9wEW1EQvkzt7qho',
    appId: '1:445998895525:android:e88cfdbacb7be25b4cd84c',
    messagingSenderId: '445998895525',
    projectId: 'galt-53dca',
    storageBucket: 'galt-53dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtv6B1M9TEebZPd1QOwRWHuqCpuL_av0s',
    appId: '1:445998895525:ios:b11c41d472fbe04c4cd84c',
    messagingSenderId: '445998895525',
    projectId: 'galt-53dca',
    storageBucket: 'galt-53dca.appspot.com',
    iosBundleId: 'me.stefanobucci.galt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtv6B1M9TEebZPd1QOwRWHuqCpuL_av0s',
    appId: '1:445998895525:ios:b11c41d472fbe04c4cd84c',
    messagingSenderId: '445998895525',
    projectId: 'galt-53dca',
    storageBucket: 'galt-53dca.appspot.com',
    iosBundleId: 'me.stefanobucci.galt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB995fLi1synr_vmgRxKAd-2qWyUeKbMW4',
    appId: '1:445998895525:web:d8ae9750803744f94cd84c',
    messagingSenderId: '445998895525',
    projectId: 'galt-53dca',
    authDomain: 'galt-53dca.firebaseapp.com',
    storageBucket: 'galt-53dca.appspot.com',
    measurementId: 'G-NE2JB379EB',
  );
}
